### ISSUE TITLE
Sort Themes Alphabetically

### ISSUE THREAD

**Issue by CecilFF4** [astronautlevel2/Anemone3DS#14]
1. Up/Down don't repeat.
2. Left/Right don't page (they scroll to the ends of the list only).
3. Some theme descriptions show invalid characters (i.e. line breaks show up as a white box with a question mark inside).
4. Themes without info.smdh show invalid information for the description/author/theme name (a theme I tested like this showed "ho" for the name, "hp" for the author, and "hq" for the description).
5. Switching to splashes when no splashes are present on the SD causes the "Failure" screen to show indefinitely.
6. Ordering of the themes in the list doesn't make much sense, but it seems like it may be based on creation date? Either way, it makes it very difficult to find what I'm looking for.

Kudos on getting the theme manager to load up the icons much faster than Themely! Honestly, I'm not ready to replace that app yet, but please keep up the good work!

**Comment by astronautlevel2** [comment]
Switched these to numbers so it's easier to keep track of things:
1, 2, 5 have been fixed.

I'm not sure what's causing 3 (line breaks work fine for me), could you send me an info.smdh that causes this?

4 is being fixed.

6, I'm not even sure what the order is. It's the order returned by FSUSER when traversing a directory.

**Comment by CecilFF4** [comment]
Yeah, this theme shows that ?box I mentioned.
[FF Curtain Call.zip](https://github.com/astronautlevel2/Anemone3DS/files/1270937/FF.Curtain.Call.zip)

**Comment by CecilFF4** [comment]
Just got back to town to test the newest Anemone3DS.

1. "White box with question mark" symbol still shows on some a variety of themes. In addition, long lines of text in the info.smdh don't wrap around. This theme has both problems.
[Zootopia - Sunset.zip](https://github.com/astronautlevel2/Anemone3DS/files/1275590/Zootopia.-.Sunset.zip)

2. Sorting by name not available.

3. As with repeating the up/down action with the control stick, can you implement a repeat of the left/right paging action with the stick as well? I have almost 200 themes and it can take a while to scroll to what I would like.

4. Could we get a live counter of how many themes we've selected for the shuffle?

Thank you for addressing my previous concerns! This is looking really good!

**Comment by Helloman892** [comment]
4. Implemented as of PR #49.

**Comment by Helloman892** [comment]
~~ignore the commit above, it's irrelevant~~

**Comment by Helloman892** [comment]
3. Implemented as of PR #51, as shown directly above.

**Comment by papermario69** [comment]
I don't know if this is relevant, but I have the latest .3dsx no cfw version, and the shuffle theme function is working fine. When I try to install a single theme, though, it freezes. Also, I figured this wouldn't work, but I tried the QR scanner and it crashed.

**Comment by astronautlevel2** [comment]
Last thing on here is sorting alphabetically, updating title accordingly

**Comment by Helloman892** [comment]
Sorting alphabetically has finally been implemented as of [commit e54c1ec](https://github.com/astronautlevel2/Anemone3DS/commit/e54c1ec655d754aaf4df9a428e0154e724f8b392) on [Anemone3DS/stable](https://github.com/astronautlevel2/Anemone3DS/commits/stable). Closing.
