### ISSUE TITLE
Logo causing console to crash when launching from the home menu

### ISSUE THREAD

**Issue by Jesse-Fan** [astronautlevel2/Anemone3DS#146]
My deivece is Old 3DS with B9S (ver1.3) Luma (ver 9.0) FBI(ver 2.5.0) 
 i downloaded your latest Anemone3DS but its not working 
![img_6779 2](https://user-images.githubusercontent.com/16611624/38427435-d0902600-39eb-11e8-987c-77b9a0b509bc.JPG)

**Comment by Helloman892** [comment]
Hi there, thanks for the report - have you tried reinstalling Anemone?

**Comment by Jesse-Fan** [comment]
@Helloman892 yes, i have tried installing it.
1.fbi titleDb
2.offline cia 
but it is not working.

**Comment by Helloman892** [comment]
Hmm, this is odd. I've spoken with one of the other developers, and he doesn't seem to know what's going on either - we also can't reproduce this with any of our testers. If we manage to find someone else suffering this issue, we'll let you know. Thanks for the report!

**Comment by astronautlevel2** [comment]
I've seen this problem a few times, it seems to be that the new banner causes a dabort in the home menu on occasion for unknown reasons. When I've experienced this problem, it only happens once and a reboot solves it - however, given that I have been unable to reliably reproduce it, I have had a hard time trying to solve it. 

Could you provide some additional information about your console? What region it is, if you've region changed, and what locale you use would all be very much appreciated.

In the meantime, I'll try to get a build to you that uses the old banner and we can see if that solves it. However, I'm out for the rest of the evening and most of tomorrow, so it may be a bit (if any of the other developers want to step up and do this that would be very much appreciated 💜)

Thank you for reporting this bug and sorry that I can't be of more help right now.

**Comment by Jesse-Fan** [comment]
@astronautlevel2 well,my old 3ds region  is TWN and use traditional Chinese language.  I have not change my region . But I don't know if the process of cracking has changed my locale. 
maybe is setup_ctrnand_luma3ds.gm9?  i run this script in GodMode9 when i update my B9S to 1.3
   that's all 
    thx 
![img_4857](https://user-images.githubusercontent.com/16611624/38452752-1ecf7bfe-3a7d-11e8-8f00-953884870720.JPG)

**Comment by LiquidFenrir** [comment]
TWN ? interesting, that's pretty rare.
You know you won't be able to use themes, right? TWN doesnt have some stuff necessary to use them. You can stil use the splashes though.  
Here's a special version of anemone, scan it with FBI. it should work for you and put you straight to the splashes:
<img src="https://cdn.discordapp.com/attachments/366999300594728960/432120417529102346/unknown.png" height=300 width=300 />

**Comment by Jesse-Fan** [comment]
@LiquidFenrir yep,
 i test it but its not work for me....
Can only run this homemade software with QR scan download, but can not be installed and also throw errors
 i have found TWN devices castrates theme functionality!!!!
so,i think that i cannot use those homebrew  change Theme ......
   THX

**Comment by LiquidFenrir** [comment]
So the first QR code didnt work, and the second QR code didn't work either? that's weird. Can you describe FBI's error message? Or take a photo

**Comment by imbicile** [comment]
At me too sometimes (if to launch the second - the third time successively) the console
new nintendo 3ds xl
Luma/FBI/Homebrew Menu latest versions
Yesterday I updated everything

**Comment by LiquidFenrir** [comment]
@imbicile Please answer these questions:

1. What region is your console?
2. Can you upload the crash dump file, or a photo of the top screen when it happens? Or tell us the LR and PC line on the top screen
3. Make sure you are using v2.0.0a and not v1.3.0

**Comment by imbicile** [comment]
I'll upload all the information later. At the moment, the console at home

**Comment by imbicile** [comment]
@LiquidFenrir 
Yes, I had version 1.3.0
I put the last 2.0.0a. But the error was again received with the 2nd time. but. After the reboot, it no longer appeared. I think that the problem is solved. Thank you
Just in case I send a dump
https://yadi.sk/d/VwUx5ba83UKrkt

**Comment by imbicile** [comment]
@LiquidFenrir 2.0.0a
Steps:
1) Removed 1.3.0
2) Install 2.0.0a
3) I started 2 times and got this dump
4) After reboot, everything works stably

**Comment by TurdPooCharger** [comment]
How many themes are in the Themes folder?

**Comment by TurdPooCharger** [comment]
Hmm, very strange. I installed .cia Anemone3DS v2.0.0a to check what this ARM11 crash dealio is. If you launch Anemone, exit out of it with HOME Menu button, launch Activity Log, exit out of that, launch Anemone again, you get that crash.

**Comment by ev1l0rd** [comment]
@TurdPooCharger That is actually due to the `recordusage` flag not being set in the icon.bin/SMDH file, which causes it to go unregistered in activity log (and iirc the friends app uses data from the activity log). It's not an attempt to 'circumvent nintendo detection' or anything. (I think most homebrew actually doesn't have this flag set).

**Comment by Helloman892** [comment]
Hi @TurdPooCharger, a couple answers:

First of all, yes, you're right - that does indeed cause a crash. As far as I can tell, however, the LR and PC of your new crash isn't the same as OP's - to that end, could you a) confirm that they are the same on your end or b) create a new issue describing this?

Secondly, we didn't 'hide the **icon.bin**' to 'avoid detection' or any such shenanigans - the reason it doesn't show up in Activity Log or on the Friends List is because of a flag not being set by us in the Makefile. It's an oversight, certainly, but nothing severe (unless, of course, this does cause the crash, in which case - thanks!).

**Comment by astronautlevel2** [comment]
The recordusage flag is entirely unrelated to the crash - we never used the recordusage flag, yet this crash has only been occuring since we used the new logo. 

I'm not sure if your activity log crash is the same crash - could you post a picture of the exception screen?

**Comment by TurdPooCharger** [comment]
@astronautlevel2, I am utterly confused as I can no longer reproduce the Activity Log crash.

Sorry if this seems too detailed or redundant. I want you guys to be sure what steps I took.

**N3DSXL (USA region), Luma3DS v9.0, original 4 GB Lexar micro SD card (FAT32 and 32 KB cluster)**
- I used injected H&S FBI to **Delete Title and Ticket** of Anemone3DS_v2.0.0.a (CRC32 hash = 55773581).
- Then I exited back to HOME Menu and waited until Anemone HOME Menu icon disappeared.
- Launched .3dsx Cthulhu_v1.3.3: Activity Log > cleared play, step, and software. Cleared shared icon cache. Clear HOME Menu icon cache.
- Pressed (Start) button to exit back onto homebrew launcher. Turned off 3DS with (Power) button.
- Turned on 3DS and waited until HOME Menu icon cache rebuilt itself.
- Launched injected FBI again to install Anemone3DS_v1.3.0 (CRC32 hash = 09C00711)
- Exited back to HOME Menu with HM button.
- Launched Anemone3DS (I have a single theme in the Theme folder).
- Exited back to HOME Menu with HM button.
- Launched Activity Log to check my HB_Launcher injected in AR Games got recorded. Noticed **Titles Played** states three (3), the hidden one is probably Anemone. The other one is H&S injected FBI.
- Exited back to HOME Menu with HM button.
- Launched injected FBI again to install Anemone3DS_v2.0.0a, without uninstalling v1.3.0.
- Exited back to HOME Menu with HM button.
- Launched Anemone again. Exited out again with HM button.
- Launched Activity Log. Exited out.
- Launched Anemone. No ARM11 crash.

I'm going to start from scratch removing v1.3.0, use Cthulhu to wipe everything, and then try installing v2.0.0a if that crash happens again. Camera on the ready for log dump picture.

Actually, would you guys like the log dump file itself? Might have been easier.

**Comment by TurdPooCharger** [comment]
I'll try testing again with procedures changed slightly. I'll use .3dsx FBI and stand alone .cia FBI instead. Although I'm fairly confident about the latest GodMode9 v1.6.3 where this ARM9 crash bug was fixed in the H&S injection, I'll like to make sure results are clean, which currently stands that they're not. BRB.

**Comment by TurdPooCharger** [comment]
Hey guys, apologies ahead of time if this is going to seem super redundant and painfully detailed. I think I found a reliable way of reproducing that ARM11 Activity Log crash. 

1. Launch .cia FBI_v2.5.0, go to **Titles**, and find Anemone3DS (doesn't matter what version).
2. **Delete Title And Ticket**. Press B to Main Menu. (HOME) button back to HOME Menu; do not use (Start) button.
3. Once you've return to HOME Menu. Wait for Anemone3DS icon to disappear.
4. Go to Homebrew Launcher and open .3dsx Cthulhu_v1.3.3.
5. Clear Activity Log play, step, & software. Clear shared icon cache. Clear HOME Menu icon cache.
6. Press (B) button until reaching Cthulhu main menu. Press (Start) to return to Homebrew launcher.
7. Wait for the loading screen to finish. 
8. Turn off the 3DS with (Power) button. Do not use Rosalina to turn off the system.
9. Remove the 3DS battery. Press and hold (power) button for 5 seconds to ensure clearing.
10. Reinsert the battery. Turn on the 3DS. Wait until HOME Menu icon cache is rebuilt.
11. Go to **HOME Menu Design** at top left corner. Turn the WiFi off under **Wireless Communication / NFC** .
12. Launch FBI and install Anemone3DS_v2.0.0a.cia . Press (B) and (HOME) buttons to return to HOME Menu.
13. Unwrap and launch Anemone3DS. Wait for everything to load. It's best to have only 1 theme in the **Themes** folder.
14. Press (HOME) button to return to HOME Menu. Do not use (Start) button.
15. Go to Activity Log and open it. Press **Next** and **OK**. Return to HOME Menu.
16. Turn off the 3DS with (Power) button. Turn it back on.
17. Open FBI again. Do not delete currently installed Anemone3DS_v2.0.0a.
18. Install Anemone_v1.3.0. Do not delete currently installed Anemone3DS_v1.3.0.
19. Install Anemone_v2.0.0a. Press (B) and (HOME) buttons to go back to HOME Menu.
20. Turn off the 3DS with (Power) button. Turn it back on.
21. Launch Anemone3DS_v2.0.0a. Press (HOME) button to return to HOME Menu. Do not use (Start) button.
22. Open Activity Log. Return to HOME Menu.
23. Launch Anemone3DS again. You should now see the dreaded ARM11 crash.

**Comment by astronautlevel2** [comment]
Currently, I'm taking a break 3 hours into a 6 hour drive, so forgive me if this comes off the wrong way. 

As I stated in a previous response, the recordusage flag doesn't fix this crash whatsoever. Logically it doesn't because we never recorded usage and didn't have this bug before. However, we also tested adding the recordusage flag on the newest build, and it didn't change anything. I am 100% confident in ruling out the recordusage flag in the list of possible causes for the bug. 

Secondly, just locking out the home button won't do anything. I have a couple reasons as to why, which I don't have time to go into right now, but if just using start gets you the crash now then locking out home button won't do anything of use. 

Finally, one thing you want to consider in your testing is that, as I described in some detail in a previous response, the new logo.bin (the screen that says anemone3ds is now loading) seems to be the

**Comment by TurdPooCharger** [comment]
@astronautlevel2, did you make sure to uninstall (ticket and title) Anemone3DS, cache clear everything with Cthulhu, reset 3DS, and then try special build with the recordusage flag?

**Comment by LiquidFenrir** [comment]
You're not supporsed to use the home button anyway. The only reason it's not blocked like some official applications do is because not enough research has been put into that.

**Comment by TurdPooCharger** [comment]
@LiquidFenrir , have you used CHMM2 and Themely before? They block off home button.

**Comment by astronautlevel2** [comment]
I've looked into their solutions before, and it's not the cleanest thing which I'd like to avoid if possible. 

1.3.0 was the first to introduce the new logo, so I'm not surprised you were able to reproduce it on 1.3.0. Try a version before that.

**Comment by TurdPooCharger** [comment]
How early do you want me to go back? v1.0.0 stable or intermediate?

**Comment by astronautlevel2** [comment]
Preferably the stable release directly before 1.3.0.

**Comment by TurdPooCharger** [comment]
@astronautlevel2 and @LiquidFenrir , before I begin I noticed there's a **settings.cfg** file within **Themes** folder. Should this be deleted?

**Comment by astronautlevel2** [comment]
I don't think it should affect things either way, it's not from us.

**Comment by TurdPooCharger** [comment]
Oo. Alright, Jerry Springer "you're not the father." teehee. :grin: 

Results: v1.2.2 is stable as a whistle with the generic home brew logo. `recordusage` ruled out at this moment. 

Next tests: I'll make a modified v1.2.2 with the Anemone logo to see if I can get it to crash. If it doesn't crash then, I'll make modified v1.3.0 and v2.0.0a with the official Nintendo logo. This is to rule out if logo is the real culprit.

**Comment by FrozenChen** [comment]
@TurdPooCharger Care to test this builds and see what happen when you run them?

1st one
https://transfer.sh/NG67G/Anemone3DS.cia

2nd one
https://transfer.sh/imoAx/Anemone3DS.cia

3rd one
https://transfer.sh/RhX3G/Anemone3DS.cia

**Comment by TurdPooCharger** [comment]
@FrozenChen, can you provide details for each of the three cia files? What was changed from the v2.0.0a stable release? Other than commits not related to logo, are all three different varieties of reworked logo?

**Comment by FrozenChen** [comment]
oh sorry, all those are latest commit Anemone with different logos

**Comment by TurdPooCharger** [comment]
Sure thing. I'm going to be on a dinner break. You'll probably hear back later in a few hours. Do you guys get bombarded with too many e-mail notifications? I don't mean to spam post if it's annoying.

**Comment by TurdPooCharger** [comment]
**Test Case #1 - NG67G (FAILED - Card Removed) :-1:** 
Was this on purpose to keep me on my toes?
![20180414_230206](https://user-images.githubusercontent.com/35666439/38775836-1c609d0c-405a-11e8-832a-aee260c3606d.png)

**Test Case #2 - imoAx (PASSED - homebrew logo)** :+1: 
Kinda boring, but it does the job.
![imoax](https://user-images.githubusercontent.com/35666439/38775848-9ceb9f62-405a-11e8-8faa-513b48be7b36.png)

**Test Case #3 - RhX3G (PASSED - PKSM Bernardo Giordano logo)** :+1: 
Gotta catch 'em all. Gotta save 'em all too.
![rhx3g](https://user-images.githubusercontent.com/35666439/38775869-e5b3285a-405a-11e8-8ac9-757e5a8d2c4c.png)

While testing those last three CIAs, I tried recreating your new logo with Every File Explorer, png2bclim, darctool3ds, and ctr-logobuilder with linux. 3DS homebrew is kinda weak on this front and linux terminal bash command go in the trash heaps. I couldn't manage to get any of them to work with injection but did notice a huge red flag with the logo's file archive.

<details>
  <summary>Click to expand</summary>
  You guys are missing hblogo_bottom.bclim in the timg directory.
</details>

**Comment by TurdPooCharger** [comment]
**Test Case # 4 - 125SMg (FAILED)** :-1: 
Crashed at its 4th launch after seeing Activity Log for the 2nd time.

Can you build one with **hblogo_bottom.bclim** with a 320x240 black/blank png?

**Comment by TurdPooCharger** [comment]
You did read the part where the crash happens with new Anemone logo on hacky v.1.2.2, right? It's definitely the logo, but if you need more confirmation that it'll cause crashes on other homebrew titles, alright then.

**Comment by TurdPooCharger** [comment]
**Test Case #5 - 4g4JR (FAILED)** :-1: 
Mode of failure exactly as Test Case #4.

@FrozenChen, do you handle developing the logo? I don't know if you caught my last edit in post with Test Case # 4, but I mentioned if you can try matching hblogo_bottom.bclim to NintendoLogo_D_00.bclyt where all 320x240 black png is viewable. If you can see the bottom .bclim within the D_00.bclyt on Every File Explorer, I think that'll fix the bug.

**Comment by FrozenChen** [comment]
I already tested it, still causes the crash, cant reproduce the crash with checkpoint tho, have been going checkpoint->activity log->checkpoint at least 10 times

**Comment by TurdPooCharger** [comment]
1. Use FBI to delete Title and Ticket for Checkpoint. 
2. Exit out with HOME button. Go to Cthulhu to clear every cache (Activity Log, shared, and HOME Menu).
3. Press (Power) button to turn off the 3DS. Remove and reinsert the battery.
4. Turn on the 3DS. Wait for the HOME Menu icon cache to rebuild.
5. Turn off the WiFi using Nintendo's Wireless Communication / NFC.
6. Launch FBI to install Checkpoint with Anemone logo. Press (Home) button to return. Do not use (Start) button.
7. Find Checkpoint. Drag and drop it close to Activity Log.
8. Unwrap and launch Checkpoint. It's probably better to have little to no games installed on the system for this.
9. Press (Home) button to return HOME Menu. Launch Activity Log. Press Next and OK. Press (Home) button to return home.
10. Launch Checkpoint again. Return back to HOME Menu again. Turn off 3DS with (Power) button.
11. Turn on 3DS. Launch Checkpoint. Go back to HOME. Launch Activity Log. Go back to HOME.
12. Launch Checkpoint. You should now ARM11 crash.
13 (cont). If you don't crash then as this does happen sometimes. Go back to HOME. Launch FBI. Go back to HOME. Launch Checkpoint. Crash.

Anything you transition from title to another, never use the (Start) or (Power) button. This is reset whatever that causes the crash.

**Comment by FrozenChen** [comment]
Well anyway, here is what you asked https://transfer.sh/uv3W0/Anemone3DS.cia bottom is 320x240

**Comment by TurdPooCharger** [comment]
**Test Case # 6 - uv3W0 (FAILED)** :-1: 
Crashes at first launch.
*Bangs head on table.* Ugghh...

I don't get how this is suppose to cause crashes unless information about the logo's 8 KB compressed limit is flat out wrong. If that's the reason why, that means Anemone's logo file was marginally stable when it's total uncompressed size sits a teensy bit too big. Adding the fully blacked out bottom picture pushed it over to the edge.
 
This is my last idea. I can't tell you if it'll work or not. This is a cropped and trimmed version of the top image to be as bare minimum as possible. Having transparency enabled cause the file size to grow bigger. Perhaps you try recreating this very same image to see if you can get it to be smaller. Try centering it while maintaining the resolution.

![hblogo_top](https://user-images.githubusercontent.com/35666439/38777383-e861e95a-4074-11e8-906c-4c64953931c2.png)

For the bottom image, have one black pixel place at one of the corners. Crossing my fingers on this one.

**Comment by TurdPooCharger** [comment]
**uv3W0** crash dump:
[crash_dump_00000134.zip](https://github.com/astronautlevel2/Anemone3DS/files/1912322/crash_dump_00000134.zip)

![uv3w0_crash_dump](https://user-images.githubusercontent.com/35666439/38777921-5ba8c60a-407e-11e8-93ac-5b2818f10aef.png)

**Comment by astronautlevel2** [comment]
Reviewing the code, Anemone should exit pretty much the exact same way through either the start or the home button. The fact that this seems to cause variance which leads to the crash makes me think that the home menu isn't properly deallocating something which leads to the logo causing some edge case crash. 

I'll try finding a way to lock down the home button as a solution in the meantime.

**Comment by TurdPooCharger** [comment]
@astronautlevel2 and @FrozenChen , I would like to test one with the top image having the black space cropped out and the bottom image with a single pixel placed where its most convenient (corner or center 0,0,0). Other homebrew logo's has theirs with smaller images. The blue wavy homebrew launcher-inspired one does image stretching to maximum size efficiency.

I can't help recreate the logo from my end due to desktop linux being uncooperative and unsure how to go about calculating and adding the missing .darc footer CMAC SHA-256 found at the way end of a decompressed logo. DarcTool3DS doesn't add this back into a rebuilt logo when recompiling it.

**Comment by FrozenChen** [comment]
no, the wave homebrew logo works because it was made with sdk tools. My guess is that the umcompressed size of the logo is the problem, something not being freed correctly by home menu(?).
Anyway i will post 2 builds, their may look the same but their inner workings are different.

1st (256kb uncompressed size)
https://transfer.sh/11GDE2/Anemone3DS.cia

2nd (132kb uncompressed size)
https://transfer.sh/NVxMo/Anemone3DS.cia

**Comment by TurdPooCharger** [comment]
**Test Case # 7 - 11GDE2 (PASSED - stability-wise)** :+1: 
YES!!! 
logo contains both top and bottom hblogo .bclim files.

![old_vs_new_logo](https://user-images.githubusercontent.com/35666439/38784677-ae5161fe-40e3-11e8-84f7-fc201f3ecae4.png)

 **(FAILED - image quality suffered)** :-1: 
I see you tried using a different png to .bclim converter. If this was done through Every File Explorer, that **CTR Layout Images option** degrades with noticeable artifacts. That's okay, baby steps!
*************
**Test Case # 8 - NVxMo (PASSED - stability)** :+1:  , **(FAILED - quality)** :-1: 
logo contains only the top hblogo .bclim
Alright, that throws out the idea you need the bottom one.

Are you using the **ctr-logobuilder** making the logo? Actually, don't answer that question.

**IF** you're using ctr-logobuilder, see if you can input bash build with one or either of these cropped top logo.
![hblogo_top2](https://user-images.githubusercontent.com/35666439/38784778-06e171fa-40e5-11e8-8960-8a21e6d3d915.png)
![hblogo_top](https://user-images.githubusercontent.com/35666439
/38784779-06fb73c0-40e5-11e8-84d0-9695a590b496.png)

`./buildlogo.sh [output name] [logo extracted folder] "0,0,0,0,0" "246,116,0,0,0" [HMAC key]`

If you intend to use the new method of bclim conversion, let me know so I can skip grading for image quality. The intention is to see if the top logo screen estate can be reduced and not fill the entire 400x240. 

If this is possible without stretching the blue Anemone name section, you should in theory be able to use your original bclim converter to maintain quality while reducing the logo's total uncompressed size.

**Comment by TurdPooCharger** [comment]
@FrozenChen, i'm posting again in case you miss my last edit.

The cropped out top logo images are 242 x 116. Double check to verify this is correct before building.

**Comment by FrozenChen** [comment]
@TurdPooCharger so my guess is was right, the uncompressed filesize of the logo is causing the crashes, those build were made just to find out in a fast way if it was the uncompressed file size so dont worry about the quality. I made this one for both quality and reduced size.

https://transfer.sh/3uYGM/Anemone3DS.cia

**Comment by TurdPooCharger** [comment]
**Test Case # 9 - 3uYGM  (PASSED WITH FLYING COLORS!!!)** :1st_place_medal: 

![screenshot_3uygm](https://user-images.githubusercontent.com/35666439/38785284-fbaa4bca-40eb-11e8-9de3-5002a8d2363a.png)

- I like the nice added touch you did for the bottom screen. Seems appropriate to include from a user's standpoint with the upside of not completely ruling out the missing bottom half could contribute to instability.
- Unless my eyes are deceiving me, the black area has a noticeably darker contrast.
- The edges along the Anemone blue rectangle seem sharper, too.

Well, time to pack it up, boys and girls. Again, sorry if there has been any trouble on my part, especially for the multiple back-to-back posts and my several presented theories that ended up being wrong. I specialize in basic GM9 scripting and not actual homebrew title development, so you'll have to forgive me for my gaps in this 3DS aspect.

Hope this leads to providing a happier user Anemone experience and glad to be of service for this issue. :)

**Comment by astronautlevel2** [comment]
Awesome, as soon as I merge in the new logo I'll close this issue.

**Comment by Bongopepe** [comment]
Hey, I'm having this same exact issue, anyone has any active links to the fixed version available?
